### PR TITLE
Adding an option to omit speaking item numbers

### PR DESCRIPTION
**Pull request by mltony**
Hi, thanks for great add-on, I use it very often! I propose to add an option to omit saying item numbers, like item 1, item2, because I find it distracting when reading large formulas. I call the option "Speak item numbers" and it is enabled by default, so existing users' experience won't be affected. Thanks!

### CODE REVIEW

**Comment by tsengwoody** [comment]
What different between using "Read of auto-generated meaning" unchecked?
in addition "Announce index of items in current frame" checked will lead to fraction will not speak it meaning when using interaction mode

**Comment by mltony** [comment]
Oh, my bad. I was looking at this announce auto-generated content option, but didn't figure out its meaning. Never mind then, I'll close this!

**Comment by Futyn-Maker** [comment]
Explaine me, please, why the option "Read of auto-generated meaning" is called that? As I've understood, this option is used to enable/disable announcing of item number in interaction mode. I can't relate the name and the meaning of this parameter...

**Comment by tsengwoody** [comment]
Interaction mode speak meaning of item is define in dictionary but in some mathml tag may have Variable number of child node.
In this case program will auto generated meaning by index.
I think it can change checkbox label let easy understand, are there any good suggestions for this label?

**Comment by Futyn-Maker** [comment]
It's becoming more understandable after reading of ReadMe. Maybe we can use "meaning of items" instead of just "meaning" on these labels? E.G. "Read of auto-generated meaning of items", but it's possible that there're better ideas.

**Comment by Futyn-Maker** [comment]
I've done it in the Russian UI-translation. Also the word "description" may be better than "meaning", but i'm not sure because my English is bad.

**Pull request closed without merging**
