### PR TITLE
Russian translation for 3.0

### PR DESCRIPTION
**Pull request by Futyn-Maker**
Please, don't merge it now if you're going to add something new before release. Else, you can merge, but I should say that Math-Text conversion doesn't work in my computer. When converting, there's an error:
```
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\__init__.py", line 762, in onTextMathAdd
    output_file = text2template(value, os.path.join(PATH, 'output', 'index.html'))
  File "C:\Users\andre\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\__init__.py", line 151, in text2template
    template = env.get_template("index.html")
  File "C:\Users\andre\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\package\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\andre\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\package\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\andre\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\package\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\andre\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\package\jinja2\loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
```
If you're in the process of development, I'm sorry.

Thanks :)

### CODE REVIEW

**Comment by tsengwoody** [comment]
I fixed template not found error.

**Comment by Futyn-Maker** [comment]
Yes, now it works fine, thanks!

Are we ready to next release, or not yet?

**Comment by cary-rowen** [comment]
If possible, I will update the simplified Chinese translation in the last two days.

**Comment by tsengwoody** [comment]
I want to clean code and refactor structure.
I will release Access8Math 3.0 when NVDA 2021.1 beta is released.

**Comment by Futyn-Maker** [comment]
OK, it's good idea. If there'll be some changes in the interface and rules, please, push it for translators.

**Comment by Futyn-Maker** [comment]
@tsengwoody very good idea with pop-up Menu to add commands.
I think it should be hidden in "Write AsciiMath" window.

Another problem is that this function seems to be depend on Keyboard Layout. It works fine if there's English Keyboard, but not if another one. It looks like it's the Keyboard macros or something like that.

**Comment by cary-rowen** [comment]
Sorry, for a digression, the version information in the "About" dialog in the access8math menu is still 2.6.
In addition, the pitch of beep is a bit low, do you feel that way?
beep(400, 100)
Is it better?
@tsengwoody

**Comment by tsengwoody** [comment]
> I think it should be hidden in "Write AsciiMath" window.
In future version. I wmay develop AsciiMath command and according cursor or edit field status to determine whether to insert LaTeX command or AsciiMath command.
> Depend on Keyboard Layout problem
I will try to solve it but I'm think it won't be that easy.

about message version information is changed.
I think low beep represent error/warning is better and I refer to instantTranslate error 120, 100 and using 100, 100.

**Comment by Futyn-Maker** [comment]
Don't understand why the about.txt file conflicts.

> I will try to solve it but I'm think it won't be that easy.

  OK, thanks. Why we can't just paste the pre-defined text when the user click on the command-option?

**Comment by cary-rowen** [comment]
it's great, but, NVDA + left / right arrow, Already used under the laptop  keyboard layout.

**Comment by tsengwoody** [comment]
update
*	Use clipboard to insert command text.
*	Press alt+leftarrow/alt+rightarrow to popup command window.

**Comment by tsengwoody** [comment]
I plan to release Access8Math 3.0 on 6/6.
If you want to update translate, please send a PR or send translate file to me before 6/5.
Thank!

**Comment by Futyn-Maker** [comment]
I don't understand what's the problem with "about.txt". Why it conflicts?
  Anyway, if you aren't planning to make changes before release, it can be merged. Thanks for your working!

**Pull request merged**
